services:
  minio:
    image: minio/minio:latest
    container_name: context-machine-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.local
    volumes:
      - ./infra/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - context-machine-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: context-machine-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.local
    volumes:
      - ./infra/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - context-machine-network

  n8n:
    image: n8nio/n8n:latest
    container_name: context-machine-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env.local
    volumes:
      - ./infra/n8n/data:/home/node/.n8n
    networks:
      - context-machine-network

  neo4j:
    image: neo4j:5
    container_name: context-machine-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env.local
    volumes:
      - ./infra/neo4j/data:/data
      - ./infra/neo4j/logs:/logs
      - ./infra/neo4j/conf:/conf
      - ./infra/neo4j/plugins:/plugins
    networks:
      - context-machine-network

  neo4j-service:
    image: context-machine-neo4j-service:latest
    container_name: context-machine-neo4j-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    volumes:
      - ./services/neo4j-service/src:/app/src
    depends_on:
      - neo4j
    networks:
      - context-machine-network
    command: flask run --reload --host=0.0.0.0 --port=3001

  analyzer-service:
    image: context-machine-analyzer-service:latest
    container_name: context-machine-analyzer-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env.local
    volumes:
      - ./services/analyzer-service/src:/app/src
    depends_on:
      - neo4j-service
    networks:
      - context-machine-network
    command: flask run --reload --host=0.0.0.0 --port=3002

networks:
  context-machine-network:
    driver: bridge
